global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
       - localhost:9090
 
  - job_name: node
    static_configs:
    - targets:
       - exporter:9100

  - job_name: blackbox
    static_configs:
    - targets:
       - blackbox:9115

  - job_name: blackbox_spec
    metrics_path: /probe
    params:
      module: [http_ipv4] #//specify the module to be used here
    static_configs:
      - targets:
        - blackbox:9115    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115