groups:
 - name: my-alerts
   rules:

   - alert: PrometheusDown
     expr: up{job="prometheus"} == 0
     for: 30s 
     labels:
       severity: critical
       team_type: infra-team
       category: up
       app_type: monitoring

   - alert: NodeExporterDown
     expr: up{job="node"} == 0
     for: 30s
     labels:
       severity: critical
       team_type: monitoring-team
       category: up
       app_type: demo-node
     annotations:
       summary: 'Node Expoter is Down!'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }}'
       app_link: 'http://localhost:9100'

   - record: job:go_app_cpu_total:available
     expr: rate(process_cpu_seconds_total{job="app-go"}[5m]) * 100

   - alert: GolangAppDown
     expr: up{job="app-go"} == 0
     for: 2m
     labels:
       severity: critical
       team_type: app-team
       category: up
       app_type: golang
     annotations:
       summary: 'DEMO 1'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }} | value: {{ $value }}% '

   - alert: PythonAppDown
     expr: up{job="app-python"} == 0
     for: 30s 
     labels:
       severity: critical
       team_type: app-team
       category: up
       app_type: python
     annotations:
       summary: 'DEMO 2'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }} | value: {{ $value }}% '
