version: '1'

networks:
  heimdall-network:
    driver: bridge

services:
  prometheus: #Prometheus Server
    image: prom/prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./service-discovery.yml:/etc/prometheus/service-discovery.yml
    ports:
      - 9090:9090

  exporter: #Exporter VM
    image: prom/node-exporter
    container_name: exporter
    ports:
      - 9100:9100