global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'example@gmail.com'
  smtp_auth_username: 'promtheus-alertmanager'
  smtp_auth_password: 'pawssword'

route:
  receiver: admin-team # fallback receiver
  group_wait: 40s
  group_interval: 5m
  repeat_interval: 30m
  routes:
  - match_re:
      team_type: (go-app|python-app)
    receiver: developer-team
    group_by: [category, app_type]
  - match_re:
      team_type: (infra)
    receiver: infra-team
    group_by: [category, app_type]
  - match_re:
      team_type: (monitoring|infra)
    receiver: monitoring-team

receivers:
 - name: admin-team
   email_configs:
    - to: admin_team@gmail.com

 - name: developer-team
   email_configs:
    - to: devloper_team@gmail.com

 - name: infra-team
   slack_configs:
    - channel: '#prometheus'
      api_url: 'https://hooks.slack.com/services/xx/xx/xxx'
      title: 'Prometheus Alerting'
      text: 'ERROR Alerting for Infra Team'

 - name: monitoring-team
   slack_configs:
    - channel: '#prometheus'
      api_url: 'https://hooks.slack.com/services/xx/xx/xxx'
      title: 'Prometheus Alerting'
      text: 'ERROR Alerting for Monitoring Team'
