global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'example@gmail.com'
  smtp_auth_username: 'promtheus-alertmanager'
  smtp_auth_password: 'pawssword'

route:
  # fallback receiver
  receiver: admin-team
  routes:
  - match_re:
      team_type: (infra|monitoring)
    receiver: monitoring-team

receivers:
 - name: admin-team
   email_configs:
    - to: receiver_email_yyy@gmail.com

 - name: monitoring-team
   email_configs:
    - to: receiver_email_xxx@gmail.com