global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
 - rules.yml

scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: node
   static_configs:
    - targets:
       - exporter:9100
 - job_name: app-go
   static_configs:
    - targets:
       - my-app-go:8888
 - job_name: app-python
   static_configs:
    - targets:
       - my-app-python:8080

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - alertmanager:9093