groups:
 - name: alert-rules
   rules:

   - alert: PrometheusDown
     expr: up{job="prometheus"} == 0
     for: 30s 
     labels:
       severity: critical
       team_type: monitoring
       category: up

   - alert: NodeExporterDown
     expr: up{job="node"} == 0
     for: 30s
     labels:
       severity: critical
       team_type: infra
       category: up
     annotations:
       summary: 'Node Expoter is Down!'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }}'
       app_link: 'http://localhost:9100'

   - record: job:go_app_cpu_total:available
     expr: rate(process_cpu_seconds_total{job="app-go"}[5m]) * 100

   - alert: App_Go_CUP_Avg
     expr: (job:go_app_cpu_total:available) > 0.45
     for: 2m
     labels:
       severity: critical
       team_type: go-app
       category: cpu
       app_type: golang
     annotations:
       summary: 'DEMO 1'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }} | value: {{ $value }}% '

   - alert: App_Python_Latency_Sec
     expr: (my_request_latency_seconds_count) > 0
     for: 2m
     labels:
       severity: warning
       team_type: python-app
       category: latency
       app_type: fastapi
     annotations:
       summary: 'DEMO 2'
       description: 'instance: {{ $labels.instance }} | job: {{ $labels.job }} | value: {{ $value }}% '
